name:               lambdatrade-common
version:            0.0.0.0
synopsis:           Common functionality for LRA applications
description:        Common functionality for Lambdatrade Reference Architecture applications.
homepage:           https://www.lambdatrade.com/
license:            BSD3
license-file:       LICENSE
author:             Lambdatrade AB
maintainer:         info@lambdatrade.com
copyright:          Lambdatrade AB, 2015
category:           Development
build-type:         Simple
extra-source-files: README.md
cabal-version:      >=1.10

library
  exposed-modules:  Lambdatrade
                  , Lambdatrade.Persistence
  build-depends:    aeson
                  , base >=4.7 && <5.0
                  , bytestring
                  , data-default
                  , esqueleto
                  , exceptions >= 0.8
                  , generic-aeson
                  , json-schema
                  , lens
                  , monad-logger
                  , mtl >= 2.2
                  , path-pieces
                  , persistent
                  , persistent-postgresql
                  , persistent-template
                  , rest-types
                  , template-haskell
                  , text
                  , time >= 1.5
                  , transformers
                  , unordered-containers
                  , uuid
  hs-source-dirs:   source
  default-language: Haskell2010