input {
  gelf {
    port => 12201

  }
}

# Parse incomming log rows

filter {
  if [message] =~ /\A{.*}\Z/ {
# Handle json-formatted log rows
    json {
      source => "message"
      add_field => {"parsed_json" => true }
      remove_field => ["message", "time"]
    }
  }
  else {
# Handle monad-logger style log rows
    grok {
      match => {message =>
        [ "\A\[%{LOGLEVEL:log_level}(#(?<component>[^\]]+))?]%{GREEDYDATA:message}\Z"
        ]}
      overwrite => ["message", "log_level"]
      add_field => {"type" => "logs"
                    "parsed_json" => false
                   }
    }
  }

# Parse logging levels
  mutate {
    lowercase => ["log_level"]
  }
  translate {
      field => "log_level"
      destination => "level"
      override => true
      dictionary =>
        [ "debug"   , "7"
        , "notice"  , "6"
        , "info"    , "5"
        , "warn"    , "4"
        , "error"   , "3"
        , "critical", "2"
        , "alert"   , "1"
        , "emerg"   , "0"
        ]
      fallback => "3"
  }
  mutate {
    convert => { "level" => "integer"}
  }


# Geo IP

  if [ip] {
    geoip {
      source => "ip"
      target => "geoip"
      add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
      add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
    }
    mutate {
      convert => [ "[geoip][coordinates]", "float" ]
    }
  }
}

output {
    elasticsearch {
      hosts => ["http://elasticsearch:9200/"]
      index => "logstash-%{instance}"
    }
}