# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.

name: servant-integration
version: '0.0.0'
synopsis: Example project showing how to integrate other handlers with servant
category: Other
description: Example project showing how to integrate other handlers with servant
maintainer: Philipp Balzarek
license: MIT

executables:
  servant-integration:
    dependencies:
    - base
    - servant-integration
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app
    extra-source-files:
    - CHANGELOG.md
    - LICENSE.md
    - package.yaml
    - README.md
    - stack.yaml
    ghc-options: -Wall

library:
  dependencies:
  - base
  - text
  - bytestring
  - mtl
  - containers
  - unordered-containers
  - aeson
  - servant
  - servant-server
  - rest-core
  - rest-wai
  - wai
  - warp
  source-dirs: src

tests:
  servant-integration-test-suite:
    dependencies:
    - base
    - servant-integration
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  servant-integration-benchmarks:
    dependencies:
    - base
    - servant-integration
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
